### ISSUE TITLE
TetherSimDriver Error

### ISSUE THREAD

**Issue by cdyoder** [rodmetoyer/tether#1]
Got the following error upon completion of the TetherSimDriver run out of the box:
Error using tetherSimDriver (line 184)
Cannot create file images\junk.avi. Permission Denied.

Also accompanied by the following command line outputs (not sure if this is related or not):
Starting simulation...
6788 successful steps
444 failed attempts
43393 function evaluations
Elapsed time is 4.043610 seconds.

**Comment by rodmetoyer** [comment]
Try now. I forgot the check for the images bin.

**Comment by cdyoder** [comment]
The mkdir code doesn't create the images directory. MATLAB believes that the images dir exists even if it does not. Easy fix of just having a standalone images directory in the file structure. 

Removed code, have permanent folder.

**Comment by rodmetoyer** [comment]
Ugh, it's because I'm being lazy. You must have a folder called images somewhere on the matlab path. I'll switch to fully qualified path and actually test it. I don't want to add an images folder or anything that serves as a bin to source control.

**Comment by rodmetoyer** [comment]
Ok, that should do it. Let me know if there are still any issues. I made it so that it creates a products folder. We can store all of the products (pics, vids, data) in that folder.
